---
title: "8130final"
author: "Mengfan Luo"
date: "23/10/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(corrplot)
#library(p8105.datasets)
#library(leaflet)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
cdi_data = read.csv("./data/cdi.csv") %>%
  janitor::clean_names() %>%
  mutate(
    cty_state = str_c(cty,",",state),
    docs_rate_1000 = 1000 * docs/pop, # Compute number of doctors/hospital beds per 1000 people.
    beds_rate_1000 = 1000 * beds/pop,
    crime_rate_1000 = 1000 * crimes/pop) %>% # Compute number of crimes per 1000 people.) 
  select(-docs,-beds,-crimes) %>%
  relocate(id,cty_state,cty)


skimr::skim(cdi_data)

numeric_cdi_df = cdi_data %>% 
  select(-cty,-state,-id,-cty_state)

corr = round(cor(numeric_cdi_df), 1)

corrplot(corr)
```


### Model construction

Data used for building model:

```{r}
cdi_model = cdi_data %>% 
  select(-id,-cty_state, -cty,-state) %>% 
  mutate(region = factor(region))
```



Backward selection

```{r}
full.fit = lm(crime_rate_1000 ~ ., data = cdi_model)
summary(full.fit) %>% 
  broom::tidy() %>%
  mutate(p_rank = rank(p.value))


step(full.fit, direction='backward')
step
```



















```{}
par(mfrow=c(3,2))

cdi_data %>% 
  hist(pop18)

cardio$age = cardio$age / 365

# hist before data cleaning
hist(cardio$age)
hist(cardio$weight)
hist(cardio$height)
hist(cardio$ap_hi)
hist(cardio$ap_lo)
```






```{}

#pop18
reg = lm(crime_rate_1000 ~ pop18, data = cdi_data)
p1 = summary(reg)$coefficients[8]
p1

cdi_data %>% 
  ggplot(aes(pop18, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="pop18", y="CRM_1000")

#pop65
reg = lm(crime_rate_1000 ~ pop65, data = cdi_data)
p2 = summary(reg)$coefficients[8]
p2

cdi_data %>% 
  ggplot(aes(pop65, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="pop65", y="CRM_1000")

#docs_rate_1000
reg = lm(crime_rate_1000 ~ docs_rate_1000, data = cdi_data)
p3 = summary(reg)$coefficients[8]
p3

cdi_data %>% 
  ggplot(aes(docs_rate_1000, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="docs_rate_1000", y="CRM_1000")

#beds_rate_1000
reg = lm(crime_rate_1000 ~ beds_rate_1000, data = cdi_data)
p4 = summary(reg)$coefficients[8]
p4

cdi_data %>% 
  ggplot(aes(beds_rate_1000, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="beds_rate_1000", y="CRM_1000")


#hsgrad
reg = lm(crime_rate_1000 ~ hsgrad, data = cdi_data)
p5 = summary(reg)$coefficients[8]
p5

cdi_data %>% 
  ggplot(aes(hsgrad, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="hsgrad", y="CRM_1000")

#bagrad
reg = lm(crime_rate_1000 ~ bagrad, data = cdi_data)
p6 = summary(reg)$coefficients[8]
p6

cdi_data %>% 
  ggplot(aes(bagrad, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="bagrad", y="CRM_1000")

#poverty
reg = lm(crime_rate_1000 ~ poverty, data = cdi_data)
p7 = summary(reg)$coefficients[8]
p7

cdi_data %>% 
  ggplot(aes(poverty, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="poverty", y="CRM_1000")

#unemp
reg = lm(crime_rate_1000 ~ unemp, data = cdi_data)
p8 = summary(reg)$coefficients[8]
p8

cdi_data %>% 
  ggplot(aes(unemp, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="unemp", y="CRM_1000")

#pcincome
reg = lm(crime_rate_1000 ~ pcincome, data = cdi_data)
p9 = summary(reg)$coefficients[8]
p9

cdi_data %>% 
  ggplot(aes(pcincome, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="pcincome", y="CRM_1000")

#totalinc
reg = lm(crime_rate_1000 ~ totalinc, data = cdi_data)
p10 = summary(reg)$coefficients[8]
p10

cdi_data %>% 
  ggplot(aes(totalinc, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="totalinc", y="CRM_1000")




sum_df = tibble(
  var = c( "pop18","pop65","docs_rate_1000","beds_rate_1000","hsgrad","bagrad","poverty","unemp","pcincome","totalinc"),
  p.value = c(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10),
  significant = p.value<0.05
) 

knitr::kable(sum_df)
```



