---
title: "8130final"
author: "Mengfan Luo"
date: "23/10/2021"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(corrplot)
library(ALSM)
#library(p8105.datasets)
#library(leaflet)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r}
cdi_data = read_csv("/Users/yushanwang/Documents/2021fall/8130BM/bm_final_project/data/cdi.csv") %>%
  janitor::clean_names() %>%
  mutate(
    cty_state = str_c(cty,",",state),
    docs_rate_1000 = 1000 * docs/pop, # Compute number of doctors/hospital beds per 1000 people.
    beds_rate_1000 = 1000 * beds/pop,
    density = as.numeric(pop)/as.numeric(area),
    crime_rate_1000 = 1000 * crimes/pop) %>% # Compute number of crimes per 1000 people. 
  dplyr::select(-docs,-beds,-crimes) %>%
  relocate(id,cty_state,cty)

knitr::kable(head(cdi_data))


numeric_cdi_df = cdi_data %>% 
  select(-cty,-state,-id,-cty_state)

corr = round(cor(numeric_cdi_df), 1)

corrplot(corr)
```


```{r}
par(mfrow=c(2,3))
boxplot(cdi_data$area,main="Area")
boxplot(cdi_data$pop,main="Population")
boxplot(cdi_data$pop18,main="Population 18-34")
boxplot(cdi_data$pop65,main="Population 65+")
boxplot(cdi_data$hsgrad,main="Highschool grads")
boxplot(cdi_data$bagrad,main="Bachelor's grads")
```





```{r}

cdi_data = cdi_data[cdi_data$area >= quantile(cdi_data$area,0.005) & cdi_data$area <= quantile(cdi_data$area,0.995),]
cdi_data = cdi_data[cdi_data$pop >= quantile(cdi_data$pop,0.005) & cdi_data$pop <= quantile(cdi_data$pop,0.995),]
cdi_data = cdi_data[cdi_data$pop18 >= quantile(cdi_data$pop18,0.005) & cdi_data$pop18 <= quantile(cdi_data$pop18,0.995),]
cdi_data = cdi_data[cdi_data$pop65 >= quantile(cdi_data$pop65,0.005) & cdi_data$pop65 <= quantile(cdi_data$pop65,0.995),]
cdi_data = cdi_data[cdi_data$hsgrad >= quantile(cdi_data$hsgrad,0.005) & cdi_data$hsgrad <= quantile(cdi_data$hsgrad,0.995),]
cdi_data = cdi_data[cdi_data$bagrad >= quantile(cdi_data$bagrad,0.005) & cdi_data$bagrad <= quantile(cdi_data$bagrad,0.995),]


par(mfrow=c(2,3))
boxplot(cdi_data$area,main="Area")
boxplot(cdi_data$pop,main="Population")
boxplot(cdi_data$pop18,main="Population 18-34")
boxplot(cdi_data$pop65,main="Population 65+")
boxplot(cdi_data$hsgrad,main="Highschool grads")
boxplot(cdi_data$bagrad,main="Bachelor's grads")


```




```{r}
par(mfrow=c(2,3))
boxplot(cdi_data$poverty,main="Poverty Rate")
boxplot(cdi_data$unemp,main="Unemployment Rate")
boxplot(cdi_data$pcincome,main="Income Per Capita")
boxplot(cdi_data$totalinc,main="Income Total")
boxplot(cdi_data$docs_rate_1000,main="Active Physicians")
boxplot(cdi_data$beds_rate_1000,main="Hospital Beds")
```






```{r}
cdi_data = cdi_data[cdi_data$poverty >= quantile(cdi_data$poverty,0.005) & cdi_data$poverty <= quantile(cdi_data$poverty,0.995),]
cdi_data = cdi_data[cdi_data$unemp >= quantile(cdi_data$unemp,0.005) & cdi_data$unemp <= quantile(cdi_data$unemp,0.995),]
cdi_data = cdi_data[cdi_data$pcincome >= quantile(cdi_data$pcincome,0.005) & cdi_data$pcincome <= quantile(cdi_data$pcincome,0.995),]
cdi_data = cdi_data[cdi_data$totalinc >= quantile(cdi_data$totalinc,0.005) & cdi_data$totalinc <= quantile(cdi_data$totalinc,0.995),]
cdi_data = cdi_data[cdi_data$docs_rate_1000 >= quantile(cdi_data$docs_rate_1000,0.005) & cdi_data$docs_rate_1000 <= quantile(cdi_data$docs_rate_1000,0.995),]
cdi_data = cdi_data[cdi_data$beds_rate_1000 >= quantile(cdi_data$beds_rate_1000,0.005) & cdi_data$beds_rate_1000 <= quantile(cdi_data$beds_rate_1000,0.995),]


par(mfrow=c(2,3))
boxplot(cdi_data$poverty,main="Poverty Rate")
boxplot(cdi_data$unemp,main="Unemployment Rate")
boxplot(cdi_data$pcincome,main="Income Per Capita")
boxplot(cdi_data$totalinc,main="Income Total")
boxplot(cdi_data$docs_rate_1000,main="Active Physicians")
boxplot(cdi_data$beds_rate_1000,main="Hospital Beds")




```


### Model construction

Data used for building model:

```{r}
cdi_model = cdi_data %>% 
  dplyr::select(-id,-cty_state, -cty,-state) %>% 
  mutate(region = factor(region))



```



Backward selection

```{r}
full.fit = lm(crime_rate_1000 ~ ., data = cdi_model)
summary(full.fit) %>% 
  broom::tidy() %>%
  mutate(p_rank = rank(p.value))


step(full.fit, direction='backward') %>% broom::tidy()
```



```{r}

full.fit = lm(crime_rate_1000 ~ ., data = cdi_model)
summary(full.fit) %>% 
  broom::tidy() %>%
  mutate(p_rank = rank(p.value))


backward = step(full.fit, direction='backward') %>%  broom::tidy() %>%  rename(backward = "term")


both = step(full.fit, direction = "both") %>% broom::tidy() %>% rename(stepwise = "term")

bind_cols(backward[-1,1],both[-1,1]) %>% knitr::kable()

```

```{r}
fit_test = lm(crime_rate_1000 ~  
                  pop + pop18 +poverty+   
                 + pcincome + totalinc + region +
                  beds_rate_1000 + density, data = cdi_model)
summary(fit_test)

```

```{r}
par(mfrow = c(2,2))
plot(fit_test)

plot(fit_test, which = 4)
```



```{}

#pop18
reg = lm(crime_rate_1000 ~ pop18, data = cdi_data)
p1 = summary(reg)$coefficients[8]
p1

cdi_data %>% 
  ggplot(aes(pop18, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="pop18", y="CRM_1000")

#pop65
reg = lm(crime_rate_1000 ~ pop65, data = cdi_data)
p2 = summary(reg)$coefficients[8]
p2

cdi_data %>% 
  ggplot(aes(pop65, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="pop65", y="CRM_1000")

#docs_rate_1000
reg = lm(crime_rate_1000 ~ docs_rate_1000, data = cdi_data)
p3 = summary(reg)$coefficients[8]
p3

cdi_data %>% 
  ggplot(aes(docs_rate_1000, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="docs_rate_1000", y="CRM_1000")

#beds_rate_1000
reg = lm(crime_rate_1000 ~ beds_rate_1000, data = cdi_data)
p4 = summary(reg)$coefficients[8]
p4

cdi_data %>% 
  ggplot(aes(beds_rate_1000, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="beds_rate_1000", y="CRM_1000")


#hsgrad
reg = lm(crime_rate_1000 ~ hsgrad, data = cdi_data)
p5 = summary(reg)$coefficients[8]
p5

cdi_data %>% 
  ggplot(aes(hsgrad, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="hsgrad", y="CRM_1000")

#bagrad
reg = lm(crime_rate_1000 ~ bagrad, data = cdi_data)
p6 = summary(reg)$coefficients[8]
p6

cdi_data %>% 
  ggplot(aes(bagrad, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="bagrad", y="CRM_1000")

#poverty
reg = lm(crime_rate_1000 ~ poverty, data = cdi_data)
p7 = summary(reg)$coefficients[8]
p7

cdi_data %>% 
  ggplot(aes(poverty, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="poverty", y="CRM_1000")

#unemp
reg = lm(crime_rate_1000 ~ unemp, data = cdi_data)
p8 = summary(reg)$coefficients[8]
p8

cdi_data %>% 
  ggplot(aes(unemp, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="unemp", y="CRM_1000")

#pcincome
reg = lm(crime_rate_1000 ~ pcincome, data = cdi_data)
p9 = summary(reg)$coefficients[8]
p9

cdi_data %>% 
  ggplot(aes(pcincome, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="pcincome", y="CRM_1000")

#totalinc
reg = lm(crime_rate_1000 ~ totalinc, data = cdi_data)
p10 = summary(reg)$coefficients[8]
p10

cdi_data %>% 
  ggplot(aes(totalinc, crime_rate_1000)) + geom_point(color='blue') + theme_bw(base_size=20) +
  geom_smooth(method='lm', se=TRUE, color='red') +
  labs(x="totalinc", y="CRM_1000")




sum_df = tibble(
  var = c( "pop18","pop65","docs_rate_1000","beds_rate_1000","hsgrad","bagrad","poverty","unemp","pcincome","totalinc"),
  p.value = c(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10),
  significant = p.value<0.05
) 

knitr::kable(sum_df)
```




