---
title: "Yushan Wang"
output: github_document
---

```{r, echo = FALSE, message=FALSE}
library(tidyverse)
library(leaps)
library(ALSM)

```

## Variable information:

```{r}
var <- c("id", "cty", "state", "area",	"pop", "pop18",	"pop65",	"docs",	"beds",	"crimes",	"hsgrad",	"bagrad",	"poverty",	"unemp",	"pcincome",	"totalinc",	"region")

var_meaning <- c("ID number", "
County name", "State name", "Land area", "Total population", "Percent of population aged 18-34", "Percent of population aged 65+", "Number of active physicians", "Number of hospital beds", "Total serious crimes", "Percent high school graduates", "Percent bachelor’s degrees
", "Percent below poverty level", "Percent unemployment", "Per capita income", "Total personal income", "Geographic region")

var_info <- data.frame(var, var_meaning)

knitr::kable(var_info)
```

## load data

```{r}
cdi_data = read_csv("./data/cdi.csv") %>%
  janitor::clean_names() %>%
  mutate(
    cty_state = str_c(cty,",",state),
    docs_rate_1000 = 1000 * docs/pop, # Compute number of doctors/hospital beds per 1000 people.
    beds_rate_1000 = 1000 * beds/pop,
    crime_rate_1000 = 1000 * crimes/pop) %>% # Compute number of crimes per 1000 people.) 
  select(-docs,-beds,-crimes) %>%
  relocate(id,cty_state,cty)

cdi_model = cdi_data %>% 
  select(-id,-cty_state, -cty,-state) %>% 
  mutate(region = factor(region))
  
```


## Criteria based selection

```{r, eval = F}

cdi_model_bestsub = 
  cdi_model %>% 
  mutate(
    region1 = ifelse(region == 1, 1, 0),
    region2 = ifelse(region == 2, 1, 0),
    region3 = ifelse(region == 3, 1, 0),
    region4 = ifelse(region == 4, 1, 1),
    region1 = factor(region1),
    region2 = factor(region2),
    region3 = factor(region3),
    region4 = factor(region4),

  ) %>% 
  select(-region) 

#mat = as.matrix(cdi_model_bestsub)
# Printing the 2 best models of each size, using the Cp criterion:
#leaps(x = mat[,c(1:12, 14:17)], y = mat[,13], nbest = 2, method = "Cp") #9

# Printing the 2 best models of each size, using the adjusted R^2 criterion:
#leaps(x = mat[,c(1:12, 14:17)], y = mat[,13], nbest = 2, method = "adjr2")

# Function regsubsets() performs a subset selection by identifying the "best" model that contains
b = regsubsets(crime_rate_1000 ~ ., data = cdi_model_bestsub)
rs = summary(b) 

# area, pop, pop18, poverty, unemp, pincome, totalinc, bed_rate_1000


# plot of Cp and Adj-R2 as functions of parameters
par(mfrow=c(1,2))

plot(2:9, rs$cp, xlab="No. of parameters", ylab="Cp Statistic") 
abline(0,1)

plot(2:9, rs$adjr2, xlab="No of parameters", ylab="Adj R2")

rs$cp #8!!!

# another way
#BestSub(cdi_model_bestsub[,c(1:13)],cdi_model_bestsub$crime_rate_1000, method = "sse", num=1) 
# results: remove unemp, pincome, docs_rate_1000

```

without region:

```{r}
# remove categorical variable: region
cdi_model_bestsub = 
  cdi_model %>% 
  select(-region)

#contrasts(cdi_model$region)

mat = as.matrix(cdi_model_bestsub)
# Printing the 2 best models of each size, using the Cp criterion:
leaps(x = mat[,1:12], y = mat[,13], nbest = 2, method = "Cp") #9

# Printing the 2 best models of each size, using the adjusted R^2 criterion:
leaps(x = mat[,1:12], y = mat[,13], nbest = 2, method = "adjr2")

# Function regsubsets() performs a subset selection by identifying the "best" model that contains
b = regsubsets(crime_rate_1000 ~ ., data = cdi_model_bestsub)
rs = summary(b) # area, pop, pop18, poverty, unemp, pincome, totalinc, bed_rate_1000
# bagrad, unemp different with stepwise

# plot of Cp and Adj-R2 as functions of parameters
par(mfrow=c(1,2))

plot(2:9, rs$cp, xlab="No. of parameters", ylab="Cp Statistic") 
abline(0,1)

plot(2:9, rs$adjr2, xlab="No of parameters", ylab="Adj R2")

rs$cp #8!!!



```

with region:

```{r}
# Function regsubsets() performs a subset selection by identifying the "best" model that contains
sb = regsubsets(crime_rate_1000 ~ ., data = cdi_model)
sumsb = summary(sb) # area, pop, pop18, poverty, unemp, pincome, totalinc, bed_rate_1000
# bagrad, unemp different with stepwise

# plot of Cp and Adj-R2 as functions of parameters
par(mfrow=c(1,2))

plot(2:9, sumsb$cp, xlab="No. of parameters", ylab="Cp Statistic") 
abline(0,1)

plot(2:9, sumsb$adjr2, xlab="No of parameters", ylab="Adj R2")

#pop pop18 poverty pcincome totalinc region3 region4 bed_rate_1000


```
